Adding a SECURITY.md file to the repository.
DhanushNehru/alien-defender-game pull request #9
Opened 2024-09-28 05:10 UTC by Brijeshthummar02

issue #2

2024-09-28 05:13 UTC, DhanushNehru requested changes
Just mention the discord server or dm in twitter to report

2024-09-28 05:26 UTC, Brijeshthummar02 commented
as mentioned i've added everything. 
And if it's fine than please do me a favor merge it in oct 1-2 when hacktoberfest starts so that i can claim merge request.

2024-10-01 15:44 UTC, Brijeshthummar02 commented
@DhanushNehru need update on this pr.

2024-10-01 17:03 UTC, DhanushNehru approved these changes

2024-10-01 17:03 UTC, merged